### ISSUE TITLE
Installation currently broken due to `crates-index` SemVer violation

### ISSUE THREAD

**Issue by str4d** [Nullus157/cargo-dl#28]
`cargo install cargo-dl` currently fails due to `cargo-dl` using `http 0.2`, but `crates-index` migrating to `http 1` (a breaking change under SemVer) in a non-breaking SemVer release. See https://github.com/frewsxcv/rust-crates-index/issues/172 for details.

Possible solutions:
- Wait for `crates-index` to fix its SemVer violation, and then either do nothing (stay on `http 0.2`), or migrate to `http 1` and `crates-index 3`.
- Migrate to `http 1` and `crates-index >= 2.10`. This however runs a risk that `crates-index` decides to fix its SemVer violation, which would break `cargo-dl` again.

**Comment by str4d** [comment]
As a temporary workaround, `cargo install --locked cargo-dl` will install with the `Cargo.lock` that was present at the time the latest `cargo-dl` version was published, i.e. with an older `crates-index`.

**Comment by Nemo157** [comment]
Fun, this is not the first time a dependency did a breaking `http` update https://github.com/algesten/ureq/issues/683. I'll wait and see what happens to avoid any breakage from fixes.

I'm disappointed I didn't catch this earlier with my nightly CI job as it got auto-disabled. I'll have to work out some way to ensure all my repos nightly jobs remain running even when they don't need continuous maintenance :thinking:.

**Comment by Nemo157** [comment]
Looks like it's been fixed upstream now. Thanks for letting me know and opening the upstream issue!
